# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  net6: '6.x'

steps:
# Setup dotnet core version
    - task: UseDotNet@2
      inputs:
        version: '$(net6)'
        includePreviewVersions: true

    # NuGet
    - task: DotNetCoreCLI@2
      displayName: 'Restore Packages'
      inputs:
        command: 'restore'
        projects: |
          RCLStaticResourceTest/RCLStaticResourceTest.csproj
          
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
       command: 'build'
       configuration: $(BuildConfiguration)
       projects: |
         RCLStaticResourceTest/RCLStaticResourceTest.csproj
       arguments: |
         --configuration $(BuildConfiguration) --no-restore
         
    - task: DotNetCoreCLI@2
      displayName: 'Pack'
      inputs:
       command: 'pack'
       configuration: $(BuildConfiguration)
       nobuild: true
       includesymbols: true
       includesource: false
       outputDir: '$(Build.ArtifactStagingDirectory)/Packages'
       packagesToPack: |
         RCLStaticResourceTest/RCLStaticResourceTest.csproj

    # Publish prepared source artifact.
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts'
      inputs:
        TargetPath: '$(Build.ArtifactStagingDirectory)/Packages/'
        artifactName: RCLStaticResourceTest
